### PR TITLE
Adding async version from Kiddooo

### PR DESCRIPTION
**Pull request by RandomGamingDev**

### CODE REVIEW

**Comment by RandomGamingDev** [comment]
Could you please fix the merge conflict? btw I already have fixes for certain issues with your code so you can just fix the merge conflict and I'll add the fixes

**Comment by 105hua** [comment]
Fixed by removing your sync code and keeping Kiddo's async code, hopefully...

**Comment by 105hua** [comment]
Resolved the merge conflict and added some missing requirements as well as added the skins directory to gitignore to prevent it from being pushed on accident.

Handing it back over to Kiddooo now to resolve an error, then you should be good.

**Comment by RandomGamingDev** [comment]
> Handing it back over to Kiddooo now to resolve an error, then you should be good.

What's the error?

Also, how'd you push to Kiddooo's repo? Did they give you permission or is there a way to do that without permission on github? I'm mostly asking because I don't see any relationship between the 2 accounts.

**Comment by RandomGamingDev** [comment]
> Fixed by removing your sync code and keeping Kiddo's async code, hopefully...

Looks good, I'll merge it soon, fix up certain parts of his code, and then add the original synchronous scraper as another option. I was thinking of adding a delay, but it doesn't look like it scans fast enough for that to be an issue, and we can worry about that once the site actually prevents it.

**Comment by 105hua** [comment]
> > Handing it back over to Kiddooo now to resolve an error, then you should be good.
> 
> What's the error?
> 
> Also, how'd you push to Kiddooo's repo? Did they give you permission or is there a way to do that without permission on github?

Something about an event in the main loop, I'll post logs in here shortly.

Kiddooo gave me permission to fix the merge conflict for them, don't worry, I'm not just some rando who fixed it 😄

**Comment by 105hua** [comment]
> > Fixed by removing your sync code and keeping Kiddo's async code, hopefully...
> 
> Looks good, I'll merge it soon, fix up certain parts of his code, and then add the original synchronous scraper as another option. I was thinking of adding a delay, but it doesn't look like it scans fast enough for that to be an issue, and we can worry about that once the site actually prevents it.

No worries, looking forward to your modifications.

**Comment by RandomGamingDev** [comment]
> Kiddooo gave me permission to fix the merge conflict for them, don't worry, I'm not just some rando who fixed it 😄

Ah, alr. I was just a bit confused since it didn't look like your accounts had any relationship with each other and I didn't know of a way to push to a github repo without permission lmao

**Comment by 105hua** [comment]
> > Kiddooo gave me permission to fix the merge conflict for them, don't worry, I'm not just some rando who fixed it 😄
> 
> Ah, alr. I was just a bit confused since it didn't look like your accounts had any relationship with each other and I didn't know of a way to push to a github repo without permission lmao

No worries, we're friends, it's all good 😃

Anyways, Kiddooo informed me that there was an error on my end and the code appears to be in working order. That being said, over to you!

**Comment by RandomGamingDev** [comment]
btw thanks to both of you for helping to make this code asynchronous I honestly didn't expect my code to even get any pull requests since it's only part of a larger (still small) project lol

**Comment by RandomGamingDev** [comment]
Hopefully, it'll serve as a great resource for those who are trying to make their own web scraper and don't want to deal with optimizing pure string manipulation, or who want a more dynamic way to do it

**Comment by RandomGamingDev** [comment]
> Anyways, Kiddooo informed me that there was an error on my end and the code appears to be in working order. That being said, over to you!

The code appears to be working for me too so I'll merge it and then add the commits. btw you guys wanna talk through discord? I was gonna originally msg Kiddooo, but I had to do so through email since his discord doesn't accept friend requests

**Pull request merged**
